(function() {
    'use strict';

    window.countryList = {
        ru: {
            name: 'Россия',
            code: 'ru',
            price: 147,
            oldPrice: 2990,
            labelPrice: 'руб.',
            phoneHelper: 'Например +7 9031234567',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            countryError: 'Страна обязательна для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            isDefault: true
        },
        az: {
            name: 'Азербайджан',
            code: 'az',
            price: 5,
            oldPrice: 79,
            labelPrice: 'манат',
            phoneHelper: 'Например +994 123456789',
            nameHelper: 'Захра Мамедова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Агдам',
            cityRandomHelper: ['Агдам', 'Агдере', 'Джебраил', 'Зангелан', 'Кельбаджар', 'Лачин', 'Физули'],
            nameRandomMaleHelper: ['Аббас Мамедов', 'Исмаилбек Аскеров', 'Данияр Алиев'],
            nameRandomFemaleHelper: ['Адия Гамбарова', 'Луиза Вагифова', 'Лязат Мехтиева', 'Махпула Джафарова'],
            dollarEquivalent: '1,5 манат',
        },
        am: {
            name: 'Армения',
            code: 'am',
            price: 1243,
            oldPrice: 27980,
            labelPrice: 'дрм',
            phoneHelper: 'Например +374 123456789',
            nameHelper: 'Мари Абитян',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Арагацотн',
            cityRandomHelper: ['Арагацотн', 'Котайк', 'Лори', 'Сюник', 'Арарат', 'Армавир', 'Вайоц Дзор', 'Гегаркуник'],
            nameRandomMaleHelper: ['Агаси Абитян', 'Вахак Айтруни', 'Гагик Баласакан', 'Давид Ваануни'],
            nameRandomFemaleHelper: ['Арусь Габелуни', 'Егине Баласакан', 'Наира Едесян', 'Меланья Зарехаванян'],
            dollarEquivalent: '433 дрм',
        },
        by: {
            name: 'Беларусь',
            code: 'by',
            price: 7,
            oldPrice: 78,
            labelPrice: 'руб.',
            phoneHelper: 'Например +375 123456789',
            nameHelper: 'Маргарыта Концява',
            nameError: 'Імя абавязковы для запаўнення',
            phoneError: 'Тэлефон абавязковы для запаўнення',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Краіна абавязковы для запаўнення',
            cityCurrentHelper: 'Минск',
            cityRandomHelper: ['Минск', 'Бобруйск', 'Витебск', 'Могилёв', 'Полоцк', 'Рогачёв', 'Гомель'],
            nameRandomMaleHelper: ['Адам Зинкевич', 'Олег Филипенко', 'Елисей Скворцов'],
            nameRandomFemaleHelper: ['Елена Полищук', 'Анна Высоцкая', 'Барбара Смолякова', 'Белла Ковальчукова'],
            dollarEquivalent: '1,68 руб',
        },
        ge: {
            name: 'Грузия',
            code: 'ge',
            price: 5,
            oldPrice: 99,
            labelPrice: 'лари',
            phoneHelper: 'Например +995 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            cityCurrentHelper: 'Тбилиси',
            cityRandomHelper: ['Тбилиси', 'Кутаиси', 'Рустави', 'Батуми', 'Гори', 'Поти', 'Зугдиди'],
            nameRandomMaleHelper: ['Георги Беридзе', 'Давити Капанадзе', 'Зураби Мамедов', 'Левани Гелашвили'],
            nameRandomFemaleHelper: ['Тамари Гогниашвили', 'Нино Гуладзе', 'Мариами Дудучава'],
            dollarEquivalent: '2,2 лари',
        },
         kz: {
            name: 'Казахстан',
            code: 'kz',
            price: 1173,
            oldPrice: 11000,
            labelPrice: 'тг.',
            phoneHelper: 'Например +77 123456789',
            nameHelper: 'Айжаксым Омарова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        kg: {
            name: 'Киргизия',
            code: 'kg',
            price: 273,
            oldPrice: 3990,
            labelPrice: 'сом',
            phoneHelper: 'Например +996 123456789',
            nameHelper: 'Жазгуль Кирдякова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
         uz: {
            name: 'Узбекистан',
            code: 'uz',
            price: 20143,
            oldPrice: 40286,
            labelPrice: 'сум',
            phoneHelper: 'Например +998 123456789',
            nameHelper: 'Гультапчан Наркисова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        md: {
            name: 'Молдавия',
            code: 'md',
            price: 43,
            oldPrice: 1200,
            labelPrice: 'лея',
            phoneHelper: 'Например +373 123456789',
            nameHelper: 'Elena Ionescu',
            nameError: 'Numele dorit pentru a umple',
            phoneError: 'Telefon necesare pentru a umple',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Țara este necesară pentru a umple',
            cityCurrentHelper: 'Бельцы',
            cityRandomHelper: ['Бельцы', 'Бричаны', 'Вулканешты', 'Дрокия', 'Калараш', 'Каушаны', 'Отачь'],
            nameRandomMaleHelper: ['Аурелиан Филипаш', 'Василе Николаеску', 'Драгош Гика', 'Космин Йонеску'],
            nameRandomFemaleHelper: ['Мария Кэпряну', 'Мариана Теодореску', 'Андра Войнеску'],
            dollarEquivalent: '16,3 лея',
        },
        ua: {
            name: 'Украина',
            code: 'ua',
            price: '73',
            oldPrice: '799',
            labelPrice: 'грн.',
            phoneHelper: 'Например +380 123456789',
            nameHelper: 'Анастасія Кравчук',
            nameError: 'Імя обовязково для заповнення',
            phoneError: 'Телефон обовязковий для заповнення',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Країна обовязковий для заповнення'
        }
    };
})();